---
- name: Get Device Facts
  hosts: all
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  vars_prompt:
  - name: USERNAME
    prompt: User name
    private: no
  - name: DEVICE_PASSWORD
    prompt: Device password
    private: yes

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: Retrieve information from devices running Junos OS
    junos_install_config:
      host={{ inventory_hostname }}
      user={{ USERNAME }}
      passwd={{ DEVICE_PASSWORD }}
      file="files/syslog.set"
      replace=no
      overwrite=no
      diffs_file="syslog_change.txt"
      comment="adding-modifying syslog statement via ansible"
    register: junos