---
- name: juniper_junos_command - Get RSI
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  vars_prompt:
    - name: USER
      prompt: Username
      private: no
    - name: PWD
      prompt: Password
      private: yes

  tasks:
    - name: CHECKING NETCONF CONNECTIVITY
      wait_for: host={{ inventory_hostname }} port=830 timeout=5
      
    - name: Request Support Information
      juniper_junos_command:
        commands: "request support information | save /var/tmp/{{ inventory_hostname }}.RSI.20171021.txt"
        timeout: 300
        dest_dir: "."
        provider:
          host: "{{ inventory_hostname }}"
          user: "{{ USER }}"
          passwd: "{{ PWD }}"
          port: 830
      register: response

    - name: Print the command output
      debug:
        var: response.stdout_lines