---
- name: juniper_junos_command - set dot1x reauthentication parameter
  hosts: switches_edge
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  vars_prompt:
    - name: USER
      prompt: Username
      private: no
    - name: PWD
      prompt: Password
      private: yes

  tasks:
    - name: CHECKING NETCONF CONNECTIVITY
      wait_for: host={{ inventory_hostname }} port=830 timeout=5
      
    - name: Load set commands from file and commit
      juniper_junos_config:
        return_output: true
        load: 'merge'
        format: 'set'
        src: "dot1x-reauth-time.set"
        comment: "Configuring dot1x reauthentication time with Ansible"
        dest_dir: "./outputs/"
        provider:
          host: "{{ inventory_hostname }}"
          user: "{{ USER }}"
          passwd: "{{ PWD }}"
          port: 830
          timeout: 600
      register: response

    - name: Print the command output
      debug:
        var: response.diff_lines
