---
- name: 'juniper_junos_config - Get Configuration of Junos devices'
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  vars_prompt:
    - name: USER
      prompt: Username
      private: no
    - name: PWD
      prompt: Password
      private: yes

  tasks:
    - name: CHECKING NETCONF CONNECTIVITY
      wait_for: host={{ inventory_hostname }} port=830 timeout=5

    - name: 'Retrieve the committed configuration'
      juniper_junos_config:
        retrieve: 'committed'
        diff: false
        check: false
        commit: false
      provider:
        host: "{{ inventory_hostname }}"
        user: "{{ USER }}"
        passwd: "{{ PWD }}"
        port: 830
      register: response

    - name: 'Print the complete response'
      debug:
        var: response