---
- name: Run Juniper CLI Commands
  hosts:  switches_edge
  connection: local
  gather_facts: false

  vars_prompt:
  - name: USER
    prompt: User name
    private: no
  - name: PWD
    prompt: Device password
    private: yes

  tasks:
    - name: CLI
      junos_command:
        commands: file archive compress source /var/log destination /var/tmp/{{ inventory_hostname }}.LOGS.20171020
        display: text
        provider:
          host: "{{ inventory_hostname }}"
          username: "{{ USER }}"
          password: "{{ PWD }}"
          port: 830

    - name: SHELL SCP COMMAND
      shell: sshpass -p {{ PWD }} scp {{ USER }}@{{ inventory_hostname }}:/var/tmp/*.*1020.tgz /usvr01-shared/ansible/.
#      copy: src={{INVENTORY_HOST}}:/var/tmp/vSRX.tgz dest=vSRX.tgz flat=yes

      register: output
    - debug: var=output.stdout_lines
